import 'package:flutter_application_radisha_admin_pannel/src/models/job_model/job_models.dart';

final List<JobModel> disputeList = [
  JobModel(
    srNo: 1,
    jobTitle: 'Gardening',
    clientName: 'Christine Brooks',
    radishaName: 'Christine Brooks',
    disputeReason: 'Job not Completed',
    dateFiled: '2024-09-10',
  ),
  JobModel(
    srNo: 2,
    jobTitle: 'Gardening',
    clientName: 'Christine Brooks',
    radishaName: 'Christine Brooks',
    disputeReason: 'Job not Completed',
    dateFiled: '2024-09-10',
  ),
  JobModel(
    srNo: 3,
    jobTitle: 'Gardening',
    clientName: 'Christine Brooks',
    radishaName: 'Christine Brooks',
    disputeReason: 'Job not Completed',
    dateFiled: '2024-09-10',
  ),
  JobModel(
    srNo: 4,
    jobTitle: 'Gardening',
    clientName: 'Christine Brooks',
    radishaName: 'Christine Brooks',
    disputeReason: 'Job not Completed',
    dateFiled: '2024-09-10',
  ),
  JobModel(
    srNo: 5,
    jobTitle: 'Cleaning',
    clientName: 'Christine Brooks',
    radishaName: 'Christine Brooks',
    disputeReason: 'Job not Completed',
    dateFiled: '2024-09-10',
  ),
  JobModel(
    srNo: 6,
    jobTitle: 'Cleaning',
    clientName: 'Christine Brooks',
    radishaName: 'Christine Brooks',
    disputeReason: 'Job not Completed',
    dateFiled: '2024-09-10',
  ),
  JobModel(
    srNo: 7,
    jobTitle: 'Gardening',
    clientName: 'Christine Brooks',
    radishaName: 'Christine Brooks',
    disputeReason: 'Job not Completed',
    dateFiled: '2024-09-10',
  ),
  JobModel(
    srNo: 8,
    jobTitle: 'Cleaning',
    clientName: 'Christine Brooks',
    radishaName: 'Christine Brooks',
    disputeReason: 'Job not Completed',
    dateFiled: '2024-09-10',
  ),
  JobModel(
    srNo: 9,
    jobTitle: 'Cleaning',
    clientName: 'Christine Brooks',
    radishaName: 'Christine Brooks',
    disputeReason: 'Job not Completed',
    dateFiled: '2024-09-10',
  ),
  JobModel(
    srNo: 10,
    jobTitle: 'Cleaning',
    clientName: 'Christine Brooks',
    radishaName: 'Christine Brooks',
    disputeReason: 'Job not Completed',
    dateFiled: '2024-09-10',
  ),
  JobModel(
    srNo: 11,
    jobTitle: 'Gardening',
    clientName: 'Christine Brooks',
    radishaName: 'Christine Brooks',
    disputeReason: 'Job not Completed',
    dateFiled: '2024-09-10',
  ),
  JobModel(
    srNo: 12,
    jobTitle: 'Gardening',
    clientName: 'Christine Brooks',
    radishaName: 'Christine Brooks',
    disputeReason: 'Job not Completed',
    dateFiled: '2024-09-10',
  ),
  JobModel(
    srNo: 13,
    jobTitle: 'Gardening',
    clientName: 'Christine Brooks',
    radishaName: 'Christine Brooks',
    disputeReason: 'Job not Completed',
    dateFiled: '2024-09-10',
  ),
  JobModel(
    srNo: 14,
    jobTitle: 'Cleaning',
    clientName: 'Christine Brooks',
    radishaName: 'Christine Brooks',
    disputeReason: 'Job not Completed',
    dateFiled: '2024-09-10',
  ),
  JobModel(
    srNo: 15,
    jobTitle: 'Cleaning',
    clientName: 'Christine Brooks',
    radishaName: 'Christine Brooks',
    disputeReason: 'Job not Completed',
    dateFiled: '2024-09-10',
  ),
  JobModel(
    srNo: 16,
    jobTitle: 'Gardening',
    clientName: 'Christine Brooks',
    radishaName: 'Christine Brooks',
    disputeReason: 'Job not Completed',
    dateFiled: '2024-09-10',
  ),
  JobModel(
    srNo: 17,
    jobTitle: 'Cleaning',
    clientName: 'Christine Brooks',
    radishaName: 'Christine Brooks',
    disputeReason: 'Job not Completed',
    dateFiled: '2024-09-10',
  ),
  JobModel(
    srNo: 18,
    jobTitle: 'Cleaning',
    clientName: 'Christine Brooks',
    radishaName: 'Christine Brooks',
    disputeReason: 'Job not Completed',
    dateFiled: '2024-09-10',
  ),
  JobModel(
    srNo: 19,
    jobTitle: 'Cleaning',
    clientName: 'Christine Brooks',
    radishaName: 'Christine Brooks',
    disputeReason: 'Job not Completed',
    dateFiled: '2024-09-10',
  ),
  JobModel(
      srNo: 20,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      completionDate: '2024-09-10',
      jobStatus: 'Completed'),
];

final List<JobModel> completedJobs = [
  JobModel(
      srNo: 1,
      jobTitle: 'Gardening',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      completionDate: '2024-09-10',
      jobStatus: 'Completed'),
  JobModel(
      srNo: 2,
      jobTitle: 'Gardening',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      completionDate: '2024-09-10',
      jobStatus: 'Completed'),
  JobModel(
      srNo: 3,
      jobTitle: 'Gardening',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      completionDate: '2024-09-10',
      jobStatus: 'Completed'),
  JobModel(
      srNo: 4,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      completionDate: '2024-09-10',
      jobStatus: 'Completed'),
  JobModel(
      srNo: 5,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      completionDate: '2024-09-10',
      jobStatus: 'Completed'),
  JobModel(
      srNo: 6,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      completionDate: '2024-09-10',
      jobStatus: 'Completed'),
  JobModel(
      srNo: 7,
      jobTitle: 'Gardening',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      completionDate: '2024-09-10',
      jobStatus: 'Completed'),
  JobModel(
      srNo: 8,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      completionDate: '2024-09-10',
      jobStatus: 'Completed'),
  JobModel(
      srNo: 9,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      completionDate: '2024-09-10',
      jobStatus: 'Completed'),
  JobModel(
      srNo: 10,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      completionDate: '2024-09-10',
      jobStatus: 'Completed'),
  JobModel(
      srNo: 11,
      jobTitle: 'Gardening',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      completionDate: '2024-09-10',
      jobStatus: 'Completed'),
  JobModel(
      srNo: 12,
      jobTitle: 'Gardening',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      completionDate: '2024-09-10',
      jobStatus: 'Completed'),
  JobModel(
      srNo: 13,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      completionDate: '2024-09-10',
      jobStatus: 'Completed'),
  JobModel(
      srNo: 14,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      completionDate: '2024-09-10',
      jobStatus: 'Completed'),
  JobModel(
      srNo: 15,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      completionDate: '2024-09-10',
      jobStatus: 'Completed'),
  JobModel(
      srNo: 16,
      jobTitle: 'Gardening',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      completionDate: '2024-09-10',
      jobStatus: 'Completed'),
  JobModel(
      srNo: 17,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      completionDate: '2024-09-10',
      jobStatus: 'Completed'),
  JobModel(
      srNo: 18,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      completionDate: '2024-09-10',
      jobStatus: 'Completed'),
  JobModel(
      srNo: 19,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      completionDate: '2024-09-10',
      jobStatus: 'Completed'),
  JobModel(
      srNo: 20,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      completionDate: '2024-09-10',
      jobStatus: 'Completed'),
];

final List<JobModel> inProgressJobs = [
  JobModel(
      srNo: 1,
      jobTitle: 'Gardening',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'In progress'),
  JobModel(
      srNo: 2,
      jobTitle: 'Gardening',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'In progress'),
  JobModel(
      srNo: 3,
      jobTitle: 'Gardening',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'In progress'),
  JobModel(
      srNo: 4,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'In progress'),
  JobModel(
      srNo: 5,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'In progress'),
  JobModel(
      srNo: 6,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'In progress'),
  JobModel(
      srNo: 7,
      jobTitle: 'Gardening',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'In progress'),
  JobModel(
      srNo: 8,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'In progress'),
  JobModel(
      srNo: 9,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'In progress'),
  JobModel(
    srNo: 10,
    jobTitle: 'Cleaning',
    clientName: 'Christine Brooks',
    radishaName: 'Christine Brooks',
    date: '2024-09-10',
    jobStatus: 'In progress',
  ),
  JobModel(
    srNo: 11,
    jobTitle: 'Cleaning',
    clientName: 'Christine Brooks',
    radishaName: 'Christine Brooks',
    date: '2024-09-10',
    jobStatus: 'In progress',
  ),
  JobModel(
    srNo: 12,
    jobTitle: 'Cleaning',
    clientName: 'Christine Brooks',
    radishaName: 'Christine Brooks',
    date: '2024-09-10',
    jobStatus: 'In progress',
  ),
  JobModel(
      srNo: 13,
      jobTitle: 'Gardening',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'In progress'),
  JobModel(
    srNo: 14,
    jobTitle: 'Cleaning',
    clientName: 'Christine Brooks',
    radishaName: 'Christine Brooks',
    date: '2024-09-10',
    jobStatus: 'In progress',
  ),
  JobModel(
      srNo: 15,
      jobTitle: 'Gardening',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'In progress'),
  JobModel(
    srNo: 16,
    jobTitle: 'Cleaning',
    clientName: 'Christine Brooks',
    radishaName: 'Christine Brooks',
    date: '2024-09-10',
    jobStatus: 'In progress',
  ),
  JobModel(
      srNo: 17,
      jobTitle: 'Gardening',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'In progress'),
  JobModel(
    srNo: 18,
    jobTitle: 'Cleaning',
    clientName: 'Christine Brooks',
    radishaName: 'Christine Brooks',
    date: '2024-09-10',
    jobStatus: 'In progress',
  ),
  JobModel(
    srNo: 19,
    jobTitle: 'Cleaning',
    clientName: 'Christine Brooks',
    radishaName: 'Christine Brooks',
    date: '2024-09-10',
    jobStatus: 'In progress',
  ),
  JobModel(
    srNo: 20,
    jobTitle: 'Cleaning',
    clientName: 'Christine Brooks',
    radishaName: 'Christine Brooks',
    date: '2024-09-10',
    jobStatus: 'In progress',
  ),
];

final List<JobModel> allJobs = [
  JobModel(
      srNo: 1,
      jobTitle: 'Gardening',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'Active'),
  JobModel(
      srNo: 2,
      jobTitle: 'Gardening',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'In progress'),
  JobModel(
      srNo: 3,
      jobTitle: 'Gardening',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'Completed'),
  JobModel(
      srNo: 4,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'Active'),
  JobModel(
      srNo: 5,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'In progress'),
  JobModel(
      srNo: 6,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'Completed'),
  JobModel(
      srNo: 7,
      jobTitle: 'Gardening',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'Active'),
  JobModel(
      srNo: 8,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'In progress'),
  JobModel(
      srNo: 9,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'Completed'),
  JobModel(
      srNo: 10,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'Dispute'),
  JobModel(
      srNo: 11,
      jobTitle: 'Painting',
      clientName: 'Mike Brown',
      radishaName: 'Mike Brown',
      date: '2024-09-11',
      jobStatus: 'Active'),
  JobModel(
      srNo: 12,
      jobTitle: 'Repairing',
      clientName: 'Anna Smith',
      radishaName: 'Anna Smith',
      date: '2024-09-12',
      jobStatus: 'Completed'),
  JobModel(
      srNo: 13,
      jobTitle: 'Plumbing',
      clientName: 'David Lee',
      radishaName: 'David Lee',
      date: '2024-09-13',
      jobStatus: 'In progress'),
  JobModel(
      srNo: 14,
      jobTitle: 'Electrical',
      clientName: 'Sarah White',
      radishaName: 'Sarah White',
      date: '2024-09-14',
      jobStatus: 'Active'),
  JobModel(
      srNo: 15,
      jobTitle: 'Carpentry',
      clientName: 'Chris Green',
      radishaName: 'Chris Green',
      date: '2024-09-15',
      jobStatus: 'Completed'),
  JobModel(
      srNo: 16,
      jobTitle: 'Cleaning',
      clientName: 'Alice Blue',
      radishaName: 'Alice Blue',
      date: '2024-09-16',
      jobStatus: 'In progress'),
  JobModel(
      srNo: 17,
      jobTitle: 'Gardening',
      clientName: 'John Doe',
      radishaName: 'John Doe',
      date: '2024-09-17',
      jobStatus: 'Dispute'),
  JobModel(
      srNo: 18,
      jobTitle: 'Cleaning',
      clientName: 'Jessica Smith',
      radishaName: 'Jessica Smith',
      date: '2024-09-18',
      jobStatus: 'Active'),
  JobModel(
      srNo: 19,
      jobTitle: 'Repairing',
      clientName: 'Luke Brown',
      radishaName: 'Luke Brown',
      date: '2024-09-19',
      jobStatus: 'Completed'),
  JobModel(
      srNo: 20,
      jobTitle: 'Painting',
      clientName: 'Emily White',
      radishaName: 'Emily White',
      date: '2024-09-20',
      jobStatus: 'In progress'),
];

final List<JobModel> activeJobs = [
  JobModel(
      srNo: 1,
      jobTitle: 'Gardening',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'Active'),
  JobModel(
      srNo: 2,
      jobTitle: 'Gardening',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'Active'),
  JobModel(
      srNo: 3,
      jobTitle: 'Gardening',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'Active'),
  JobModel(
      srNo: 4,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'Active'),
  JobModel(
      srNo: 5,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'Active'),
  JobModel(
      srNo: 6,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'Active'),
  JobModel(
      srNo: 7,
      jobTitle: 'Gardening',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'Active'),
  JobModel(
      srNo: 8,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'Active'),
  JobModel(
      srNo: 9,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'Active'),
  JobModel(
      srNo: 10,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'Active'),
  JobModel(
      srNo: 11,
      jobTitle: 'Gardening',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'Active'),
  JobModel(
      srNo: 12,
      jobTitle: 'Gardening',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'Active'),
  JobModel(
      srNo: 13,
      jobTitle: 'Gardening',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'Active'),
  JobModel(
      srNo: 14,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'Active'),
  JobModel(
      srNo: 15,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'Active'),
  JobModel(
      srNo: 16,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'Active'),
  JobModel(
      srNo: 17,
      jobTitle: 'Gardening',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'Active'),
  JobModel(
      srNo: 18,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'Active'),
  JobModel(
      srNo: 19,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'Active'),
  JobModel(
      srNo: 20,
      jobTitle: 'Cleaning',
      clientName: 'Christine Brooks',
      radishaName: 'Christine Brooks',
      date: '2024-09-10',
      jobStatus: 'Active'),
];
